### ISSUE TITLE
$.removeCookie is not a recognized on Chrome

### ISSUE THREAD

**Issue by estevaosa** [carhartl/jquery-cookie#386] opened 2016-03-03 15:23 UTC
Hello guys, how are you?

A problem appeared for me a few days ago, I have been working in this solution, even though, I was not able to find yet, maybe you can help me.

I'm using the jquery-cookie in my project, I developed it in my local host (mac). 

The function $.removeCookie works fine in all browsers in my local machine, when I put the code in the server (google clouding - ubunto) the function $.removeCookie is not recognized on Chrome, but the others browsers works well including mobile version. 

In chrome I'm able to create the cookie by function $cookie, but not to delete.

The code is: 
$.cookie("identificacao", data[0].ID_PJ, {expires: 1, path: '/'})
$.removeCookie('identificacao', {path: '/'});

The error is: Uncaught TypeError: $.removeCookie is not a function

Do you have some suggestion? 

Regards
Estevão

**Comment by carhartl** [comment] 2016-03-03 15:43
I have absolutely no idea what might be causing it, is there a way to look at the code/problem online?

**Comment by estevaosa** [comment] 2016-03-03 16:45
Hi, I'm thinking how to show the code on line. You can see the problem clicking in this link:

http://www.paymenu.com.br/login.html

After click on the button "login" you will be able to see the error in the console using chrome, with the other browsers everything works fine.

You don't need to fill the user and the password, just click on the button login. 

is it enough? 

Regards

**Comment by carhartl** [comment] 2016-03-03 17:48
First thing I saw is you're including both jquery.cookie.js and the newer js.cookie.js... you should settle on one of them, preferably js.cookie.js, which is the one that is being maintained.

**Comment by estevaosa** [comment] 2016-03-03 21:28
I took of the file jquery.cookie.js, the error stiil there. Very interesting, it look like that the chrome is not seeing the js.cookie.js ...

**Comment by FagnerMartinsBrack** [comment] 2016-03-04 11:03
@estevaosa Can you please provide a simple example that reproduces the issue? Otherwise this seems to be a usage problem and therefore you have a best chance of getting a response if you ask on [StackOverflow](http://stackoverflow.com/questions/tagged/js-cookie).

I suggest either using js-cookie v1.5.1 if you want `$.cookie` or `$.removeCookie` APIs, because since `2.0.0` those APIs were changes to `Cookies.set`, `Cookies.get` and `Cookies.remove`.

**Comment by estevaosa** [comment] 2016-03-04 17:52
@FagnerMartinsBrack thank you for the answer. I done exactly what you said, now everything is fine. I made a new download of js.cookie.js and I used the Cookies.set, Cookies.get and Cookies.remove.

Thank you @carhartl and @FagnerMartinsBrack 

Regards
Estevão

**Comment by FagnerMartinsBrack** [comment] 2016-03-05 02:02
Glad you solved it, closing then :+1:

**Closed as completed by FagnerMartinsBrack** 2016-03-05 02:02 UTC
