### ISSUE TITLE
Request - version bump on js files or revert master

### ISSUE THREAD

**Issue by jvanasco** [carhartl/jquery-cookie#380] opened 2015-12-04 19:00 UTC
Preface: I know this project is not maintained any longer.

I'm looking to upgrade to the new non-jquery version and checked to see if there were any fixes since the 1.4.1 release I have in the interim.

I noticed that these lines still reads 1.4.1 -
- https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js#L2
- https://github.com/carhartl/jquery-cookie/blob/master/bower.json#L3
- https://github.com/carhartl/jquery-cookie/blob/master/component.json#L5
- https://github.com/carhartl/jquery-cookie/blob/master/cookie.jquery.json#L3
- https://github.com/carhartl/jquery-cookie/blob/master/package.json#L3

Since this project is essentially shut down and the commits since 1.4.1 won't be integrated, I wanted to suggest either:
- Roll "master" back to the 1.4.1 release (the current master can be a working version or something)
- Update the 1.4.1 release number in `master` to `1.4.2-dev` or `1.4.2-unreleased`

**Comment by FagnerMartinsBrack** [comment] 2015-12-04 23:35
I don't understand exactly what is the problem. [1.4.1 is the latest release](https://www.npmjs.com/package/jquery.cookie) for jquery.cookie. js-cookie started from https://github.com/js-cookie/js-cookie/commit/4527b3725ce7b61066e6aa12bbe8d20c0371a1d7 up to the [version 1.5.0](https://github.com/js-cookie/js-cookie/releases/tag/v1.5.0), which contains everything this repo has, except the notices.
- The problem with hard reset is that it will break forks.
- Releasing a new version doesn't seems to make sense because everything here is contained in the version 1.5.0 anyway.

Btw, the master branch should not be used in production because it is, by default, an unstable branch. The only version that should be considered here is the ones that were released up to 1.4.1.

**Comment by jvanasco** [comment] 2015-12-04 23:46
I'm not suggesting a new release.  I'm suggesting that either the "master" branch of this project roll-back to the 1.4.1 release, or that the files be tagged "1.4.2-dev" (but no new release made).

The reason is because the master branch is not actually "1.4.1" -- it has a lot of commits since then, but the repo's design makes it look like master is 1.4.1.  I

**Comment by FagnerMartinsBrack** [comment] 2015-12-04 23:52
> The reason is because the master branch is not actually "1.4.1"

Now I got it, it can be confusing for people that copies the code directly from the source without checking the releases page. Is that it?

**Comment by carhartl** [comment] 2015-12-04 23:55
So you expect the master branch to practically match a release, like in the git flow model?

**Comment by jvanasco** [comment] 2015-12-05 00:45
@FagnerMartinsBrack yes.  If someone looks at this repo and says "ok, let's just see what the last update here is..." then looks at the file, they get the unreleased version not the actual 1.4.1

@carhartl I'm a fan of that model, but not expecting it. Many projects might use a "-dev" or other placeholder version in their master branch, or bump the version number up to the forthcoming release.  This repo is weird/misleading because there is a "1.4.1" tag, but the "master" branch used for development has files labeled "1.4.1" as well.  It suggests that the master and the tag are the same, but master is many commits ahead.

**Comment by FagnerMartinsBrack** [comment] 2015-12-05 01:03
I am convinced that changing the version number to `1.4.2-unreleased` or `1.4.2-frozen` for all relevant files in master (without publishing it on npm) is a reasonable request to prevent further confusion.

@carhartl what do you think?

**Comment by FagnerMartinsBrack** [comment] 2016-03-04 10:58
@jvanasco sorry to take too long, [here is the Pull Request](https://github.com/carhartl/jquery-cookie/pull/388), care to take a look?

**Comment by carhartl** [comment] 2016-03-04 11:02
I still haven't unterstood up to this day what the problem is.

**Comment by FagnerMartinsBrack** [comment] 2016-03-04 11:12
> I still haven't unterstood up to this day what the problem is.

Basically if he goes to the [Releases page](https://github.com/carhartl/jquery-cookie/releases/tag/v1.4.1) it says:

> 39 commits to master since this release

This will make one to assume that there were additional important fixes on this repository after 1.4.1 which weren't released with 1.4.1. We know it is not the case and all commits went to the new repo, but those ending up here don't know that. Since most people jump straight to the version in the source file or json metadata to check the actual version, `1.4.2-unreleased` provides a clear hint that the commits belong to a non released version 1.4.2.

Other solution is to create an actual new 1.4.2 release and publish on npm so that `master` is not too far away from the latest release.

@jvanasco please correct me if I am wrong.

**Comment by FagnerMartinsBrack** [comment] 2016-03-05 03:08
@carhartl @jvanasco I will leave #388 open, if there is no feedback for a few days I will just merge it to close this issue, then we can monitor if anybody else will have this kind of problem in the future.

Does that makes sense?

**Comment by jvanasco** [comment] 2016-03-05 03:38
Looks good.

That's a good distillation of the confusion.  

Also, If you search online for the latest version, you'll end up seeing the current master which is really "1.4.2-unreleased" and not 1.4.1 as labeled.  So it can be confusing to see what version is really running -- especially if junior devs are checking in the file.

**Comment by FagnerMartinsBrack** [comment] 2016-04-17 13:13
It seems this s going nowhere, as from [this comment](https://github.com/carhartl/jquery-cookie/pull/388#issuecomment-195008179).

I have added the following to the version 1.4.1 in the releases page, I hope this at least clarifies for those who don't read the README and go straight to the [releases page](https://github.com/carhartl/jquery-cookie/releases):

> **Note:**
> This is the last version on this repository. To see all the versions, check the [new repository](https://github.com/js-cookie/js-cookie/releases).
> 
> For more information, see [this comment](https://github.com/carhartl/jquery-cookie/issues/349#issuecomment-116822133).

**Closed as completed by FagnerMartinsBrack** 2016-04-17 13:13 UTC
